name: traka
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0
  ably_flutter: ^1.2.22
  bloc: ^8.1.2
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  google_sign_in: ^6.1.6
  github_sign_in_plus: ^0.0.2
  firebase_auth: ^4.14.0
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.1.0
  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/res/
    - assets/svgs/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
